version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: workchecker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432"  # PostgreSQL container'ı 5432 portunu dış dünyaya açıyor

  djangoapp:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db  # Django app, db servisine bağımlı
    networks:
      - app_network
    environment:
      - DB_HOST=db  # db servisi, PostgreSQL container'ı
      - DB_PORT=5432  # PostgreSQL'in varsayılan portu 5432
      - DB_NAME=workchecker
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
